baseURL = "https://brickjourney.anthonyoconnor.ca/"
languageCode = "en-us"
title = "Brick Journey"
theme = "hugo-bricks"


preserveTaxonomyNames = true

[[menu.main]]
    name = "About"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Videos"
    url = "/videos"
    weight = 2

[[menu.main]]
    name = "Photos"
    url = "/photos"
    weight = 3
